// ONNX Protocol Buffer definitions
// This is a subset of the ONNX specification needed for checkpoint functionality
// Based on ONNX v1.13.0 specification

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: checkpoints/onnx.proto

package checkpoints

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tensor data types
type TensorProto_DataType int32

const (
	TensorProto_DataType_UNDEFINED  TensorProto_DataType = 0
	TensorProto_DataType_FLOAT      TensorProto_DataType = 1 // float32
	TensorProto_DataType_UINT8      TensorProto_DataType = 2 // uint8
	TensorProto_DataType_INT8       TensorProto_DataType = 3 // int8
	TensorProto_DataType_UINT16     TensorProto_DataType = 4 // uint16
	TensorProto_DataType_INT16      TensorProto_DataType = 5 // int16
	TensorProto_DataType_INT32      TensorProto_DataType = 6 // int32
	TensorProto_DataType_INT64      TensorProto_DataType = 7 // int64
	TensorProto_DataType_STRING     TensorProto_DataType = 8 // string
	TensorProto_DataType_BOOL       TensorProto_DataType = 9 // bool
	TensorProto_DataType_FLOAT16    TensorProto_DataType = 10
	TensorProto_DataType_DOUBLE     TensorProto_DataType = 11
	TensorProto_DataType_UINT32     TensorProto_DataType = 12
	TensorProto_DataType_UINT64     TensorProto_DataType = 13
	TensorProto_DataType_COMPLEX64  TensorProto_DataType = 14
	TensorProto_DataType_COMPLEX128 TensorProto_DataType = 15
	TensorProto_DataType_BFLOAT16   TensorProto_DataType = 16
)

// Enum value maps for TensorProto_DataType.
var (
	TensorProto_DataType_name = map[int32]string{
		0:  "UNDEFINED",
		1:  "FLOAT",
		2:  "UINT8",
		3:  "INT8",
		4:  "UINT16",
		5:  "INT16",
		6:  "INT32",
		7:  "INT64",
		8:  "STRING",
		9:  "BOOL",
		10: "FLOAT16",
		11: "DOUBLE",
		12: "UINT32",
		13: "UINT64",
		14: "COMPLEX64",
		15: "COMPLEX128",
		16: "BFLOAT16",
	}
	TensorProto_DataType_value = map[string]int32{
		"UNDEFINED":  0,
		"FLOAT":      1,
		"UINT8":      2,
		"INT8":       3,
		"UINT16":     4,
		"INT16":      5,
		"INT32":      6,
		"INT64":      7,
		"STRING":     8,
		"BOOL":       9,
		"FLOAT16":    10,
		"DOUBLE":     11,
		"UINT32":     12,
		"UINT64":     13,
		"COMPLEX64":  14,
		"COMPLEX128": 15,
		"BFLOAT16":   16,
	}
)

func (x TensorProto_DataType) Enum() *TensorProto_DataType {
	p := new(TensorProto_DataType)
	*p = x
	return p
}

func (x TensorProto_DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TensorProto_DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_checkpoints_onnx_proto_enumTypes[0].Descriptor()
}

func (TensorProto_DataType) Type() protoreflect.EnumType {
	return &file_checkpoints_onnx_proto_enumTypes[0]
}

func (x TensorProto_DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TensorProto_DataType.Descriptor instead.
func (TensorProto_DataType) EnumDescriptor() ([]byte, []int) {
	return file_checkpoints_onnx_proto_rawDescGZIP(), []int{0}
}

// Attribute types
type AttributeProto_AttributeType int32

const (
	AttributeProto_AttributeType_UNDEFINED_ATTR      AttributeProto_AttributeType = 0
	AttributeProto_AttributeType_FLOAT_ATTR          AttributeProto_AttributeType = 1
	AttributeProto_AttributeType_INT_ATTR            AttributeProto_AttributeType = 2
	AttributeProto_AttributeType_STRING_ATTR         AttributeProto_AttributeType = 3
	AttributeProto_AttributeType_TENSOR_ATTR         AttributeProto_AttributeType = 4
	AttributeProto_AttributeType_GRAPH_ATTR          AttributeProto_AttributeType = 5
	AttributeProto_AttributeType_SPARSE_TENSOR_ATTR  AttributeProto_AttributeType = 11
	AttributeProto_AttributeType_TYPE_PROTO_ATTR     AttributeProto_AttributeType = 13
	AttributeProto_AttributeType_FLOATS_ATTR         AttributeProto_AttributeType = 6
	AttributeProto_AttributeType_INTS_ATTR           AttributeProto_AttributeType = 7
	AttributeProto_AttributeType_STRINGS_ATTR        AttributeProto_AttributeType = 8
	AttributeProto_AttributeType_TENSORS_ATTR        AttributeProto_AttributeType = 9
	AttributeProto_AttributeType_GRAPHS_ATTR         AttributeProto_AttributeType = 10
	AttributeProto_AttributeType_SPARSE_TENSORS_ATTR AttributeProto_AttributeType = 12
	AttributeProto_AttributeType_TYPE_PROTOS_ATTR    AttributeProto_AttributeType = 14
)

// Enum value maps for AttributeProto_AttributeType.
var (
	AttributeProto_AttributeType_name = map[int32]string{
		0:  "UNDEFINED_ATTR",
		1:  "FLOAT_ATTR",
		2:  "INT_ATTR",
		3:  "STRING_ATTR",
		4:  "TENSOR_ATTR",
		5:  "GRAPH_ATTR",
		11: "SPARSE_TENSOR_ATTR",
		13: "TYPE_PROTO_ATTR",
		6:  "FLOATS_ATTR",
		7:  "INTS_ATTR",
		8:  "STRINGS_ATTR",
		9:  "TENSORS_ATTR",
		10: "GRAPHS_ATTR",
		12: "SPARSE_TENSORS_ATTR",
		14: "TYPE_PROTOS_ATTR",
	}
	AttributeProto_AttributeType_value = map[string]int32{
		"UNDEFINED_ATTR":      0,
		"FLOAT_ATTR":          1,
		"INT_ATTR":            2,
		"STRING_ATTR":         3,
		"TENSOR_ATTR":         4,
		"GRAPH_ATTR":          5,
		"SPARSE_TENSOR_ATTR":  11,
		"TYPE_PROTO_ATTR":     13,
		"FLOATS_ATTR":         6,
		"INTS_ATTR":           7,
		"STRINGS_ATTR":        8,
		"TENSORS_ATTR":        9,
		"GRAPHS_ATTR":         10,
		"SPARSE_TENSORS_ATTR": 12,
		"TYPE_PROTOS_ATTR":    14,
	}
)

func (x AttributeProto_AttributeType) Enum() *AttributeProto_AttributeType {
	p := new(AttributeProto_AttributeType)
	*p = x
	return p
}

func (x AttributeProto_AttributeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttributeProto_AttributeType) Descriptor() protoreflect.EnumDescriptor {
	return file_checkpoints_onnx_proto_enumTypes[1].Descriptor()
}

func (AttributeProto_AttributeType) Type() protoreflect.EnumType {
	return &file_checkpoints_onnx_proto_enumTypes[1]
}

func (x AttributeProto_AttributeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttributeProto_AttributeType.Descriptor instead.
func (AttributeProto_AttributeType) EnumDescriptor() ([]byte, []int) {
	return file_checkpoints_onnx_proto_rawDescGZIP(), []int{1}
}

// Versioning
type Version struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IrVersion     int64                  `protobuf:"varint,1,opt,name=ir_version,json=irVersion,proto3" json:"ir_version,omitempty"`
	ModelVersion  int64                  `protobuf:"varint,2,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_checkpoints_onnx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_checkpoints_onnx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_checkpoints_onnx_proto_rawDescGZIP(), []int{0}
}

func (x *Version) GetIrVersion() int64 {
	if x != nil {
		return x.IrVersion
	}
	return 0
}

func (x *Version) GetModelVersion() int64 {
	if x != nil {
		return x.ModelVersion
	}
	return 0
}

// Operator Set
type OperatorSetIdProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorSetIdProto) Reset() {
	*x = OperatorSetIdProto{}
	mi := &file_checkpoints_onnx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorSetIdProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorSetIdProto) ProtoMessage() {}

func (x *OperatorSetIdProto) ProtoReflect() protoreflect.Message {
	mi := &file_checkpoints_onnx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorSetIdProto.ProtoReflect.Descriptor instead.
func (*OperatorSetIdProto) Descriptor() ([]byte, []int) {
	return file_checkpoints_onnx_proto_rawDescGZIP(), []int{1}
}

func (x *OperatorSetIdProto) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *OperatorSetIdProto) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// Dimension of a tensor shape
type TensorShapeProto struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Dim           []*TensorShapeProto_Dimension `protobuf:"bytes,1,rep,name=dim,proto3" json:"dim,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TensorShapeProto) Reset() {
	*x = TensorShapeProto{}
	mi := &file_checkpoints_onnx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TensorShapeProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TensorShapeProto) ProtoMessage() {}

func (x *TensorShapeProto) ProtoReflect() protoreflect.Message {
	mi := &file_checkpoints_onnx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TensorShapeProto.ProtoReflect.Descriptor instead.
func (*TensorShapeProto) Descriptor() ([]byte, []int) {
	return file_checkpoints_onnx_proto_rawDescGZIP(), []int{2}
}

func (x *TensorShapeProto) GetDim() []*TensorShapeProto_Dimension {
	if x != nil {
		return x.Dim
	}
	return nil
}

// Type of a tensor
type TypeProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*TypeProto_TensorType
	Value         isTypeProto_Value `protobuf_oneof:"value"`
	Denotation    string            `protobuf:"bytes,6,opt,name=denotation,proto3" json:"denotation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeProto) Reset() {
	*x = TypeProto{}
	mi := &file_checkpoints_onnx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeProto) ProtoMessage() {}

func (x *TypeProto) ProtoReflect() protoreflect.Message {
	mi := &file_checkpoints_onnx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeProto.ProtoReflect.Descriptor instead.
func (*TypeProto) Descriptor() ([]byte, []int) {
	return file_checkpoints_onnx_proto_rawDescGZIP(), []int{3}
}

func (x *TypeProto) GetValue() isTypeProto_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *TypeProto) GetTensorType() *TypeProto_Tensor {
	if x != nil {
		if x, ok := x.Value.(*TypeProto_TensorType); ok {
			return x.TensorType
		}
	}
	return nil
}

func (x *TypeProto) GetDenotation() string {
	if x != nil {
		return x.Denotation
	}
	return ""
}

type isTypeProto_Value interface {
	isTypeProto_Value()
}

type TypeProto_TensorType struct {
	TensorType *TypeProto_Tensor `protobuf:"bytes,1,opt,name=tensor_type,json=tensorType,proto3,oneof"`
}

func (*TypeProto_TensorType) isTypeProto_Value() {}

// ValueInfo
type ValueInfoProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          *TypeProto             `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	DocString     string                 `protobuf:"bytes,3,opt,name=doc_string,json=docString,proto3" json:"doc_string,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueInfoProto) Reset() {
	*x = ValueInfoProto{}
	mi := &file_checkpoints_onnx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueInfoProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueInfoProto) ProtoMessage() {}

func (x *ValueInfoProto) ProtoReflect() protoreflect.Message {
	mi := &file_checkpoints_onnx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueInfoProto.ProtoReflect.Descriptor instead.
func (*ValueInfoProto) Descriptor() ([]byte, []int) {
	return file_checkpoints_onnx_proto_rawDescGZIP(), []int{4}
}

func (x *ValueInfoProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ValueInfoProto) GetType() *TypeProto {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ValueInfoProto) GetDocString() string {
	if x != nil {
		return x.DocString
	}
	return ""
}

// Attribute definition
type AttributeProto struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Name          string                       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RefAttrName   string                       `protobuf:"bytes,21,opt,name=ref_attr_name,json=refAttrName,proto3" json:"ref_attr_name,omitempty"`
	DocString     string                       `protobuf:"bytes,13,opt,name=doc_string,json=docString,proto3" json:"doc_string,omitempty"`
	Type          AttributeProto_AttributeType `protobuf:"varint,20,opt,name=type,proto3,enum=checkpoints.AttributeProto_AttributeType" json:"type,omitempty"`
	F             float32                      `protobuf:"fixed32,2,opt,name=f,proto3" json:"f,omitempty"`
	I             int64                        `protobuf:"varint,3,opt,name=i,proto3" json:"i,omitempty"`
	S             []byte                       `protobuf:"bytes,4,opt,name=s,proto3" json:"s,omitempty"`
	T             *TensorProto                 `protobuf:"bytes,5,opt,name=t,proto3" json:"t,omitempty"`
	G             *GraphProto                  `protobuf:"bytes,6,opt,name=g,proto3" json:"g,omitempty"`
	SparseTensor  *SparseTensorProto           `protobuf:"bytes,22,opt,name=sparse_tensor,json=sparseTensor,proto3" json:"sparse_tensor,omitempty"`
	Tp            *TypeProto                   `protobuf:"bytes,14,opt,name=tp,proto3" json:"tp,omitempty"`
	Floats        []float32                    `protobuf:"fixed32,7,rep,packed,name=floats,proto3" json:"floats,omitempty"`
	Ints          []int64                      `protobuf:"varint,8,rep,packed,name=ints,proto3" json:"ints,omitempty"`
	Strings       [][]byte                     `protobuf:"bytes,9,rep,name=strings,proto3" json:"strings,omitempty"`
	Tensors       []*TensorProto               `protobuf:"bytes,10,rep,name=tensors,proto3" json:"tensors,omitempty"`
	Graphs        []*GraphProto                `protobuf:"bytes,11,rep,name=graphs,proto3" json:"graphs,omitempty"`
	SparseTensors []*SparseTensorProto         `protobuf:"bytes,23,rep,name=sparse_tensors,json=sparseTensors,proto3" json:"sparse_tensors,omitempty"`
	TypeProtos    []*TypeProto                 `protobuf:"bytes,15,rep,name=type_protos,json=typeProtos,proto3" json:"type_protos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeProto) Reset() {
	*x = AttributeProto{}
	mi := &file_checkpoints_onnx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeProto) ProtoMessage() {}

func (x *AttributeProto) ProtoReflect() protoreflect.Message {
	mi := &file_checkpoints_onnx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeProto.ProtoReflect.Descriptor instead.
func (*AttributeProto) Descriptor() ([]byte, []int) {
	return file_checkpoints_onnx_proto_rawDescGZIP(), []int{5}
}

func (x *AttributeProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AttributeProto) GetRefAttrName() string {
	if x != nil {
		return x.RefAttrName
	}
	return ""
}

func (x *AttributeProto) GetDocString() string {
	if x != nil {
		return x.DocString
	}
	return ""
}

func (x *AttributeProto) GetType() AttributeProto_AttributeType {
	if x != nil {
		return x.Type
	}
	return AttributeProto_AttributeType_UNDEFINED_ATTR
}

func (x *AttributeProto) GetF() float32 {
	if x != nil {
		return x.F
	}
	return 0
}

func (x *AttributeProto) GetI() int64 {
	if x != nil {
		return x.I
	}
	return 0
}

func (x *AttributeProto) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *AttributeProto) GetT() *TensorProto {
	if x != nil {
		return x.T
	}
	return nil
}

func (x *AttributeProto) GetG() *GraphProto {
	if x != nil {
		return x.G
	}
	return nil
}

func (x *AttributeProto) GetSparseTensor() *SparseTensorProto {
	if x != nil {
		return x.SparseTensor
	}
	return nil
}

func (x *AttributeProto) GetTp() *TypeProto {
	if x != nil {
		return x.Tp
	}
	return nil
}

func (x *AttributeProto) GetFloats() []float32 {
	if x != nil {
		return x.Floats
	}
	return nil
}

func (x *AttributeProto) GetInts() []int64 {
	if x != nil {
		return x.Ints
	}
	return nil
}

func (x *AttributeProto) GetStrings() [][]byte {
	if x != nil {
		return x.Strings
	}
	return nil
}

func (x *AttributeProto) GetTensors() []*TensorProto {
	if x != nil {
		return x.Tensors
	}
	return nil
}

func (x *AttributeProto) GetGraphs() []*GraphProto {
	if x != nil {
		return x.Graphs
	}
	return nil
}

func (x *AttributeProto) GetSparseTensors() []*SparseTensorProto {
	if x != nil {
		return x.SparseTensors
	}
	return nil
}

func (x *AttributeProto) GetTypeProtos() []*TypeProto {
	if x != nil {
		return x.TypeProtos
	}
	return nil
}

// Tensor
type TensorProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dims          []int64                `protobuf:"varint,1,rep,packed,name=dims,proto3" json:"dims,omitempty"`
	DataType      TensorProto_DataType   `protobuf:"varint,2,opt,name=data_type,json=dataType,proto3,enum=checkpoints.TensorProto_DataType" json:"data_type,omitempty"`
	Segment       *TensorProto_Segment   `protobuf:"bytes,3,opt,name=segment,proto3" json:"segment,omitempty"`
	FloatData     []float32              `protobuf:"fixed32,4,rep,packed,name=float_data,json=floatData,proto3" json:"float_data,omitempty"`
	Int32Data     []int32                `protobuf:"varint,5,rep,packed,name=int32_data,json=int32Data,proto3" json:"int32_data,omitempty"`
	StringData    [][]byte               `protobuf:"bytes,6,rep,name=string_data,json=stringData,proto3" json:"string_data,omitempty"`
	Int64Data     []int64                `protobuf:"varint,7,rep,packed,name=int64_data,json=int64Data,proto3" json:"int64_data,omitempty"`
	Name          string                 `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	DocString     string                 `protobuf:"bytes,12,opt,name=doc_string,json=docString,proto3" json:"doc_string,omitempty"`
	RawData       []byte                 `protobuf:"bytes,9,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	DoubleData    []float64              `protobuf:"fixed64,10,rep,packed,name=double_data,json=doubleData,proto3" json:"double_data,omitempty"`
	Uint64Data    []uint64               `protobuf:"varint,11,rep,packed,name=uint64_data,json=uint64Data,proto3" json:"uint64_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TensorProto) Reset() {
	*x = TensorProto{}
	mi := &file_checkpoints_onnx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TensorProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TensorProto) ProtoMessage() {}

func (x *TensorProto) ProtoReflect() protoreflect.Message {
	mi := &file_checkpoints_onnx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TensorProto.ProtoReflect.Descriptor instead.
func (*TensorProto) Descriptor() ([]byte, []int) {
	return file_checkpoints_onnx_proto_rawDescGZIP(), []int{6}
}

func (x *TensorProto) GetDims() []int64 {
	if x != nil {
		return x.Dims
	}
	return nil
}

func (x *TensorProto) GetDataType() TensorProto_DataType {
	if x != nil {
		return x.DataType
	}
	return TensorProto_DataType_UNDEFINED
}

func (x *TensorProto) GetSegment() *TensorProto_Segment {
	if x != nil {
		return x.Segment
	}
	return nil
}

func (x *TensorProto) GetFloatData() []float32 {
	if x != nil {
		return x.FloatData
	}
	return nil
}

func (x *TensorProto) GetInt32Data() []int32 {
	if x != nil {
		return x.Int32Data
	}
	return nil
}

func (x *TensorProto) GetStringData() [][]byte {
	if x != nil {
		return x.StringData
	}
	return nil
}

func (x *TensorProto) GetInt64Data() []int64 {
	if x != nil {
		return x.Int64Data
	}
	return nil
}

func (x *TensorProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TensorProto) GetDocString() string {
	if x != nil {
		return x.DocString
	}
	return ""
}

func (x *TensorProto) GetRawData() []byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

func (x *TensorProto) GetDoubleData() []float64 {
	if x != nil {
		return x.DoubleData
	}
	return nil
}

func (x *TensorProto) GetUint64Data() []uint64 {
	if x != nil {
		return x.Uint64Data
	}
	return nil
}

// SparseTensor (minimal for compatibility)
type SparseTensorProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        *TensorProto           `protobuf:"bytes,1,opt,name=values,proto3" json:"values,omitempty"`
	Indices       *TensorProto           `protobuf:"bytes,2,opt,name=indices,proto3" json:"indices,omitempty"`
	Dims          []int64                `protobuf:"varint,3,rep,packed,name=dims,proto3" json:"dims,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SparseTensorProto) Reset() {
	*x = SparseTensorProto{}
	mi := &file_checkpoints_onnx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SparseTensorProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SparseTensorProto) ProtoMessage() {}

func (x *SparseTensorProto) ProtoReflect() protoreflect.Message {
	mi := &file_checkpoints_onnx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SparseTensorProto.ProtoReflect.Descriptor instead.
func (*SparseTensorProto) Descriptor() ([]byte, []int) {
	return file_checkpoints_onnx_proto_rawDescGZIP(), []int{7}
}

func (x *SparseTensorProto) GetValues() *TensorProto {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *SparseTensorProto) GetIndices() *TensorProto {
	if x != nil {
		return x.Indices
	}
	return nil
}

func (x *SparseTensorProto) GetDims() []int64 {
	if x != nil {
		return x.Dims
	}
	return nil
}

// Node - represents a computation operation
type NodeProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         []string               `protobuf:"bytes,1,rep,name=input,proto3" json:"input,omitempty"`
	Output        []string               `protobuf:"bytes,2,rep,name=output,proto3" json:"output,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	OpType        string                 `protobuf:"bytes,4,opt,name=op_type,json=opType,proto3" json:"op_type,omitempty"`
	Domain        string                 `protobuf:"bytes,7,opt,name=domain,proto3" json:"domain,omitempty"`
	Attribute     []*AttributeProto      `protobuf:"bytes,5,rep,name=attribute,proto3" json:"attribute,omitempty"`
	DocString     string                 `protobuf:"bytes,6,opt,name=doc_string,json=docString,proto3" json:"doc_string,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeProto) Reset() {
	*x = NodeProto{}
	mi := &file_checkpoints_onnx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeProto) ProtoMessage() {}

func (x *NodeProto) ProtoReflect() protoreflect.Message {
	mi := &file_checkpoints_onnx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeProto.ProtoReflect.Descriptor instead.
func (*NodeProto) Descriptor() ([]byte, []int) {
	return file_checkpoints_onnx_proto_rawDescGZIP(), []int{8}
}

func (x *NodeProto) GetInput() []string {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *NodeProto) GetOutput() []string {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *NodeProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeProto) GetOpType() string {
	if x != nil {
		return x.OpType
	}
	return ""
}

func (x *NodeProto) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *NodeProto) GetAttribute() []*AttributeProto {
	if x != nil {
		return x.Attribute
	}
	return nil
}

func (x *NodeProto) GetDocString() string {
	if x != nil {
		return x.DocString
	}
	return ""
}

// Graph
type GraphProto struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Node                   []*NodeProto           `protobuf:"bytes,1,rep,name=node,proto3" json:"node,omitempty"`
	Name                   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Initializer            []*TensorProto         `protobuf:"bytes,5,rep,name=initializer,proto3" json:"initializer,omitempty"`
	SparseInitializer      []*SparseTensorProto   `protobuf:"bytes,15,rep,name=sparse_initializer,json=sparseInitializer,proto3" json:"sparse_initializer,omitempty"`
	DocString              string                 `protobuf:"bytes,10,opt,name=doc_string,json=docString,proto3" json:"doc_string,omitempty"`
	Input                  []*ValueInfoProto      `protobuf:"bytes,11,rep,name=input,proto3" json:"input,omitempty"`
	Output                 []*ValueInfoProto      `protobuf:"bytes,12,rep,name=output,proto3" json:"output,omitempty"`
	ValueInfo              []*ValueInfoProto      `protobuf:"bytes,13,rep,name=value_info,json=valueInfo,proto3" json:"value_info,omitempty"`
	QuantizationAnnotation []*TensorAnnotation    `protobuf:"bytes,14,rep,name=quantization_annotation,json=quantizationAnnotation,proto3" json:"quantization_annotation,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GraphProto) Reset() {
	*x = GraphProto{}
	mi := &file_checkpoints_onnx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphProto) ProtoMessage() {}

func (x *GraphProto) ProtoReflect() protoreflect.Message {
	mi := &file_checkpoints_onnx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphProto.ProtoReflect.Descriptor instead.
func (*GraphProto) Descriptor() ([]byte, []int) {
	return file_checkpoints_onnx_proto_rawDescGZIP(), []int{9}
}

func (x *GraphProto) GetNode() []*NodeProto {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *GraphProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GraphProto) GetInitializer() []*TensorProto {
	if x != nil {
		return x.Initializer
	}
	return nil
}

func (x *GraphProto) GetSparseInitializer() []*SparseTensorProto {
	if x != nil {
		return x.SparseInitializer
	}
	return nil
}

func (x *GraphProto) GetDocString() string {
	if x != nil {
		return x.DocString
	}
	return ""
}

func (x *GraphProto) GetInput() []*ValueInfoProto {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *GraphProto) GetOutput() []*ValueInfoProto {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *GraphProto) GetValueInfo() []*ValueInfoProto {
	if x != nil {
		return x.ValueInfo
	}
	return nil
}

func (x *GraphProto) GetQuantizationAnnotation() []*TensorAnnotation {
	if x != nil {
		return x.QuantizationAnnotation
	}
	return nil
}

// TensorAnnotation
type TensorAnnotation struct {
	state                     protoimpl.MessageState    `protogen:"open.v1"`
	TensorName                string                    `protobuf:"bytes,1,opt,name=tensor_name,json=tensorName,proto3" json:"tensor_name,omitempty"`
	QuantParameterTensorNames []*StringStringEntryProto `protobuf:"bytes,2,rep,name=quant_parameter_tensor_names,json=quantParameterTensorNames,proto3" json:"quant_parameter_tensor_names,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *TensorAnnotation) Reset() {
	*x = TensorAnnotation{}
	mi := &file_checkpoints_onnx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TensorAnnotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TensorAnnotation) ProtoMessage() {}

func (x *TensorAnnotation) ProtoReflect() protoreflect.Message {
	mi := &file_checkpoints_onnx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TensorAnnotation.ProtoReflect.Descriptor instead.
func (*TensorAnnotation) Descriptor() ([]byte, []int) {
	return file_checkpoints_onnx_proto_rawDescGZIP(), []int{10}
}

func (x *TensorAnnotation) GetTensorName() string {
	if x != nil {
		return x.TensorName
	}
	return ""
}

func (x *TensorAnnotation) GetQuantParameterTensorNames() []*StringStringEntryProto {
	if x != nil {
		return x.QuantParameterTensorNames
	}
	return nil
}

// StringStringEntry
type StringStringEntryProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringStringEntryProto) Reset() {
	*x = StringStringEntryProto{}
	mi := &file_checkpoints_onnx_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringStringEntryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringStringEntryProto) ProtoMessage() {}

func (x *StringStringEntryProto) ProtoReflect() protoreflect.Message {
	mi := &file_checkpoints_onnx_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringStringEntryProto.ProtoReflect.Descriptor instead.
func (*StringStringEntryProto) Descriptor() ([]byte, []int) {
	return file_checkpoints_onnx_proto_rawDescGZIP(), []int{11}
}

func (x *StringStringEntryProto) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StringStringEntryProto) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Model
type ModelProto struct {
	state           protoimpl.MessageState    `protogen:"open.v1"`
	IrVersion       int64                     `protobuf:"varint,1,opt,name=ir_version,json=irVersion,proto3" json:"ir_version,omitempty"`
	OpsetImport     []*OperatorSetIdProto     `protobuf:"bytes,8,rep,name=opset_import,json=opsetImport,proto3" json:"opset_import,omitempty"`
	ProducerName    string                    `protobuf:"bytes,2,opt,name=producer_name,json=producerName,proto3" json:"producer_name,omitempty"`
	ProducerVersion string                    `protobuf:"bytes,3,opt,name=producer_version,json=producerVersion,proto3" json:"producer_version,omitempty"`
	Domain          string                    `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	ModelVersion    int64                     `protobuf:"varint,5,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	DocString       string                    `protobuf:"bytes,6,opt,name=doc_string,json=docString,proto3" json:"doc_string,omitempty"`
	Graph           *GraphProto               `protobuf:"bytes,7,opt,name=graph,proto3" json:"graph,omitempty"`
	MetadataProps   []*StringStringEntryProto `protobuf:"bytes,14,rep,name=metadata_props,json=metadataProps,proto3" json:"metadata_props,omitempty"`
	TrainingInfo    []*TrainingInfoProto      `protobuf:"bytes,20,rep,name=training_info,json=trainingInfo,proto3" json:"training_info,omitempty"`
	Functions       []*FunctionProto          `protobuf:"bytes,25,rep,name=functions,proto3" json:"functions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ModelProto) Reset() {
	*x = ModelProto{}
	mi := &file_checkpoints_onnx_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelProto) ProtoMessage() {}

func (x *ModelProto) ProtoReflect() protoreflect.Message {
	mi := &file_checkpoints_onnx_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelProto.ProtoReflect.Descriptor instead.
func (*ModelProto) Descriptor() ([]byte, []int) {
	return file_checkpoints_onnx_proto_rawDescGZIP(), []int{12}
}

func (x *ModelProto) GetIrVersion() int64 {
	if x != nil {
		return x.IrVersion
	}
	return 0
}

func (x *ModelProto) GetOpsetImport() []*OperatorSetIdProto {
	if x != nil {
		return x.OpsetImport
	}
	return nil
}

func (x *ModelProto) GetProducerName() string {
	if x != nil {
		return x.ProducerName
	}
	return ""
}

func (x *ModelProto) GetProducerVersion() string {
	if x != nil {
		return x.ProducerVersion
	}
	return ""
}

func (x *ModelProto) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ModelProto) GetModelVersion() int64 {
	if x != nil {
		return x.ModelVersion
	}
	return 0
}

func (x *ModelProto) GetDocString() string {
	if x != nil {
		return x.DocString
	}
	return ""
}

func (x *ModelProto) GetGraph() *GraphProto {
	if x != nil {
		return x.Graph
	}
	return nil
}

func (x *ModelProto) GetMetadataProps() []*StringStringEntryProto {
	if x != nil {
		return x.MetadataProps
	}
	return nil
}

func (x *ModelProto) GetTrainingInfo() []*TrainingInfoProto {
	if x != nil {
		return x.TrainingInfo
	}
	return nil
}

func (x *ModelProto) GetFunctions() []*FunctionProto {
	if x != nil {
		return x.Functions
	}
	return nil
}

// TrainingInfo (minimal)
type TrainingInfoProto struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Initialization *GraphProto            `protobuf:"bytes,1,opt,name=initialization,proto3" json:"initialization,omitempty"`
	Algorithm      *GraphProto            `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TrainingInfoProto) Reset() {
	*x = TrainingInfoProto{}
	mi := &file_checkpoints_onnx_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingInfoProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingInfoProto) ProtoMessage() {}

func (x *TrainingInfoProto) ProtoReflect() protoreflect.Message {
	mi := &file_checkpoints_onnx_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingInfoProto.ProtoReflect.Descriptor instead.
func (*TrainingInfoProto) Descriptor() ([]byte, []int) {
	return file_checkpoints_onnx_proto_rawDescGZIP(), []int{13}
}

func (x *TrainingInfoProto) GetInitialization() *GraphProto {
	if x != nil {
		return x.Initialization
	}
	return nil
}

func (x *TrainingInfoProto) GetAlgorithm() *GraphProto {
	if x != nil {
		return x.Algorithm
	}
	return nil
}

// Function (minimal)
type FunctionProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Input         []string               `protobuf:"bytes,4,rep,name=input,proto3" json:"input,omitempty"`
	Output        []string               `protobuf:"bytes,5,rep,name=output,proto3" json:"output,omitempty"`
	Attribute     []string               `protobuf:"bytes,6,rep,name=attribute,proto3" json:"attribute,omitempty"`
	Node          []*NodeProto           `protobuf:"bytes,7,rep,name=node,proto3" json:"node,omitempty"`
	DocString     string                 `protobuf:"bytes,8,opt,name=doc_string,json=docString,proto3" json:"doc_string,omitempty"`
	OpsetImport   []*OperatorSetIdProto  `protobuf:"bytes,9,rep,name=opset_import,json=opsetImport,proto3" json:"opset_import,omitempty"`
	Domain        string                 `protobuf:"bytes,10,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionProto) Reset() {
	*x = FunctionProto{}
	mi := &file_checkpoints_onnx_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionProto) ProtoMessage() {}

func (x *FunctionProto) ProtoReflect() protoreflect.Message {
	mi := &file_checkpoints_onnx_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionProto.ProtoReflect.Descriptor instead.
func (*FunctionProto) Descriptor() ([]byte, []int) {
	return file_checkpoints_onnx_proto_rawDescGZIP(), []int{14}
}

func (x *FunctionProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionProto) GetInput() []string {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *FunctionProto) GetOutput() []string {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *FunctionProto) GetAttribute() []string {
	if x != nil {
		return x.Attribute
	}
	return nil
}

func (x *FunctionProto) GetNode() []*NodeProto {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *FunctionProto) GetDocString() string {
	if x != nil {
		return x.DocString
	}
	return ""
}

func (x *FunctionProto) GetOpsetImport() []*OperatorSetIdProto {
	if x != nil {
		return x.OpsetImport
	}
	return nil
}

func (x *FunctionProto) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type TensorShapeProto_Dimension struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*TensorShapeProto_Dimension_DimValue
	//	*TensorShapeProto_Dimension_DimParam
	Value         isTensorShapeProto_Dimension_Value `protobuf_oneof:"value"`
	Denotation    string                             `protobuf:"bytes,3,opt,name=denotation,proto3" json:"denotation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TensorShapeProto_Dimension) Reset() {
	*x = TensorShapeProto_Dimension{}
	mi := &file_checkpoints_onnx_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TensorShapeProto_Dimension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TensorShapeProto_Dimension) ProtoMessage() {}

func (x *TensorShapeProto_Dimension) ProtoReflect() protoreflect.Message {
	mi := &file_checkpoints_onnx_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TensorShapeProto_Dimension.ProtoReflect.Descriptor instead.
func (*TensorShapeProto_Dimension) Descriptor() ([]byte, []int) {
	return file_checkpoints_onnx_proto_rawDescGZIP(), []int{2, 0}
}

func (x *TensorShapeProto_Dimension) GetValue() isTensorShapeProto_Dimension_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *TensorShapeProto_Dimension) GetDimValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*TensorShapeProto_Dimension_DimValue); ok {
			return x.DimValue
		}
	}
	return 0
}

func (x *TensorShapeProto_Dimension) GetDimParam() string {
	if x != nil {
		if x, ok := x.Value.(*TensorShapeProto_Dimension_DimParam); ok {
			return x.DimParam
		}
	}
	return ""
}

func (x *TensorShapeProto_Dimension) GetDenotation() string {
	if x != nil {
		return x.Denotation
	}
	return ""
}

type isTensorShapeProto_Dimension_Value interface {
	isTensorShapeProto_Dimension_Value()
}

type TensorShapeProto_Dimension_DimValue struct {
	DimValue int64 `protobuf:"varint,1,opt,name=dim_value,json=dimValue,proto3,oneof"`
}

type TensorShapeProto_Dimension_DimParam struct {
	DimParam string `protobuf:"bytes,2,opt,name=dim_param,json=dimParam,proto3,oneof"`
}

func (*TensorShapeProto_Dimension_DimValue) isTensorShapeProto_Dimension_Value() {}

func (*TensorShapeProto_Dimension_DimParam) isTensorShapeProto_Dimension_Value() {}

type TypeProto_Tensor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ElemType      TensorProto_DataType   `protobuf:"varint,1,opt,name=elem_type,json=elemType,proto3,enum=checkpoints.TensorProto_DataType" json:"elem_type,omitempty"`
	Shape         *TensorShapeProto      `protobuf:"bytes,2,opt,name=shape,proto3" json:"shape,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeProto_Tensor) Reset() {
	*x = TypeProto_Tensor{}
	mi := &file_checkpoints_onnx_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeProto_Tensor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeProto_Tensor) ProtoMessage() {}

func (x *TypeProto_Tensor) ProtoReflect() protoreflect.Message {
	mi := &file_checkpoints_onnx_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeProto_Tensor.ProtoReflect.Descriptor instead.
func (*TypeProto_Tensor) Descriptor() ([]byte, []int) {
	return file_checkpoints_onnx_proto_rawDescGZIP(), []int{3, 0}
}

func (x *TypeProto_Tensor) GetElemType() TensorProto_DataType {
	if x != nil {
		return x.ElemType
	}
	return TensorProto_DataType_UNDEFINED
}

func (x *TypeProto_Tensor) GetShape() *TensorShapeProto {
	if x != nil {
		return x.Shape
	}
	return nil
}

type TensorProto_Segment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Begin         int64                  `protobuf:"varint,1,opt,name=begin,proto3" json:"begin,omitempty"`
	End           int64                  `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TensorProto_Segment) Reset() {
	*x = TensorProto_Segment{}
	mi := &file_checkpoints_onnx_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TensorProto_Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TensorProto_Segment) ProtoMessage() {}

func (x *TensorProto_Segment) ProtoReflect() protoreflect.Message {
	mi := &file_checkpoints_onnx_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TensorProto_Segment.ProtoReflect.Descriptor instead.
func (*TensorProto_Segment) Descriptor() ([]byte, []int) {
	return file_checkpoints_onnx_proto_rawDescGZIP(), []int{6, 0}
}

func (x *TensorProto_Segment) GetBegin() int64 {
	if x != nil {
		return x.Begin
	}
	return 0
}

func (x *TensorProto_Segment) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

var File_checkpoints_onnx_proto protoreflect.FileDescriptor

const file_checkpoints_onnx_proto_rawDesc = "" +
	"\n" +
	"\x16checkpoints/onnx.proto\x12\vcheckpoints\"M\n" +
	"\aVersion\x12\x1d\n" +
	"\n" +
	"ir_version\x18\x01 \x01(\x03R\tirVersion\x12#\n" +
	"\rmodel_version\x18\x02 \x01(\x03R\fmodelVersion\"F\n" +
	"\x12OperatorSetIdProto\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\"\xc1\x01\n" +
	"\x10TensorShapeProto\x129\n" +
	"\x03dim\x18\x01 \x03(\v2'.checkpoints.TensorShapeProto.DimensionR\x03dim\x1ar\n" +
	"\tDimension\x12\x1d\n" +
	"\tdim_value\x18\x01 \x01(\x03H\x00R\bdimValue\x12\x1d\n" +
	"\tdim_param\x18\x02 \x01(\tH\x00R\bdimParam\x12\x1e\n" +
	"\n" +
	"denotation\x18\x03 \x01(\tR\n" +
	"denotationB\a\n" +
	"\x05value\"\xf5\x01\n" +
	"\tTypeProto\x12@\n" +
	"\vtensor_type\x18\x01 \x01(\v2\x1d.checkpoints.TypeProto.TensorH\x00R\n" +
	"tensorType\x12\x1e\n" +
	"\n" +
	"denotation\x18\x06 \x01(\tR\n" +
	"denotation\x1a}\n" +
	"\x06Tensor\x12>\n" +
	"\telem_type\x18\x01 \x01(\x0e2!.checkpoints.TensorProto_DataTypeR\belemType\x123\n" +
	"\x05shape\x18\x02 \x01(\v2\x1d.checkpoints.TensorShapeProtoR\x05shapeB\a\n" +
	"\x05value\"o\n" +
	"\x0eValueInfoProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\x04type\x18\x02 \x01(\v2\x16.checkpoints.TypeProtoR\x04type\x12\x1d\n" +
	"\n" +
	"doc_string\x18\x03 \x01(\tR\tdocString\"\xb7\x05\n" +
	"\x0eAttributeProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\rref_attr_name\x18\x15 \x01(\tR\vrefAttrName\x12\x1d\n" +
	"\n" +
	"doc_string\x18\r \x01(\tR\tdocString\x12=\n" +
	"\x04type\x18\x14 \x01(\x0e2).checkpoints.AttributeProto_AttributeTypeR\x04type\x12\f\n" +
	"\x01f\x18\x02 \x01(\x02R\x01f\x12\f\n" +
	"\x01i\x18\x03 \x01(\x03R\x01i\x12\f\n" +
	"\x01s\x18\x04 \x01(\fR\x01s\x12&\n" +
	"\x01t\x18\x05 \x01(\v2\x18.checkpoints.TensorProtoR\x01t\x12%\n" +
	"\x01g\x18\x06 \x01(\v2\x17.checkpoints.GraphProtoR\x01g\x12C\n" +
	"\rsparse_tensor\x18\x16 \x01(\v2\x1e.checkpoints.SparseTensorProtoR\fsparseTensor\x12&\n" +
	"\x02tp\x18\x0e \x01(\v2\x16.checkpoints.TypeProtoR\x02tp\x12\x16\n" +
	"\x06floats\x18\a \x03(\x02R\x06floats\x12\x12\n" +
	"\x04ints\x18\b \x03(\x03R\x04ints\x12\x18\n" +
	"\astrings\x18\t \x03(\fR\astrings\x122\n" +
	"\atensors\x18\n" +
	" \x03(\v2\x18.checkpoints.TensorProtoR\atensors\x12/\n" +
	"\x06graphs\x18\v \x03(\v2\x17.checkpoints.GraphProtoR\x06graphs\x12E\n" +
	"\x0esparse_tensors\x18\x17 \x03(\v2\x1e.checkpoints.SparseTensorProtoR\rsparseTensors\x127\n" +
	"\vtype_protos\x18\x0f \x03(\v2\x16.checkpoints.TypeProtoR\n" +
	"typeProtos\"\xf2\x03\n" +
	"\vTensorProto\x12\x12\n" +
	"\x04dims\x18\x01 \x03(\x03R\x04dims\x12>\n" +
	"\tdata_type\x18\x02 \x01(\x0e2!.checkpoints.TensorProto_DataTypeR\bdataType\x12:\n" +
	"\asegment\x18\x03 \x01(\v2 .checkpoints.TensorProto.SegmentR\asegment\x12!\n" +
	"\n" +
	"float_data\x18\x04 \x03(\x02B\x02\x10\x01R\tfloatData\x12!\n" +
	"\n" +
	"int32_data\x18\x05 \x03(\x05B\x02\x10\x01R\tint32Data\x12\x1f\n" +
	"\vstring_data\x18\x06 \x03(\fR\n" +
	"stringData\x12!\n" +
	"\n" +
	"int64_data\x18\a \x03(\x03B\x02\x10\x01R\tint64Data\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"doc_string\x18\f \x01(\tR\tdocString\x12\x19\n" +
	"\braw_data\x18\t \x01(\fR\arawData\x12#\n" +
	"\vdouble_data\x18\n" +
	" \x03(\x01B\x02\x10\x01R\n" +
	"doubleData\x12#\n" +
	"\vuint64_data\x18\v \x03(\x04B\x02\x10\x01R\n" +
	"uint64Data\x1a1\n" +
	"\aSegment\x12\x14\n" +
	"\x05begin\x18\x01 \x01(\x03R\x05begin\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x03R\x03end\"\x8d\x01\n" +
	"\x11SparseTensorProto\x120\n" +
	"\x06values\x18\x01 \x01(\v2\x18.checkpoints.TensorProtoR\x06values\x122\n" +
	"\aindices\x18\x02 \x01(\v2\x18.checkpoints.TensorProtoR\aindices\x12\x12\n" +
	"\x04dims\x18\x03 \x03(\x03R\x04dims\"\xd8\x01\n" +
	"\tNodeProto\x12\x14\n" +
	"\x05input\x18\x01 \x03(\tR\x05input\x12\x16\n" +
	"\x06output\x18\x02 \x03(\tR\x06output\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x17\n" +
	"\aop_type\x18\x04 \x01(\tR\x06opType\x12\x16\n" +
	"\x06domain\x18\a \x01(\tR\x06domain\x129\n" +
	"\tattribute\x18\x05 \x03(\v2\x1b.checkpoints.AttributeProtoR\tattribute\x12\x1d\n" +
	"\n" +
	"doc_string\x18\x06 \x01(\tR\tdocString\"\xf2\x03\n" +
	"\n" +
	"GraphProto\x12*\n" +
	"\x04node\x18\x01 \x03(\v2\x16.checkpoints.NodeProtoR\x04node\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12:\n" +
	"\vinitializer\x18\x05 \x03(\v2\x18.checkpoints.TensorProtoR\vinitializer\x12M\n" +
	"\x12sparse_initializer\x18\x0f \x03(\v2\x1e.checkpoints.SparseTensorProtoR\x11sparseInitializer\x12\x1d\n" +
	"\n" +
	"doc_string\x18\n" +
	" \x01(\tR\tdocString\x121\n" +
	"\x05input\x18\v \x03(\v2\x1b.checkpoints.ValueInfoProtoR\x05input\x123\n" +
	"\x06output\x18\f \x03(\v2\x1b.checkpoints.ValueInfoProtoR\x06output\x12:\n" +
	"\n" +
	"value_info\x18\r \x03(\v2\x1b.checkpoints.ValueInfoProtoR\tvalueInfo\x12V\n" +
	"\x17quantization_annotation\x18\x0e \x03(\v2\x1d.checkpoints.TensorAnnotationR\x16quantizationAnnotation\"\x99\x01\n" +
	"\x10TensorAnnotation\x12\x1f\n" +
	"\vtensor_name\x18\x01 \x01(\tR\n" +
	"tensorName\x12d\n" +
	"\x1cquant_parameter_tensor_names\x18\x02 \x03(\v2#.checkpoints.StringStringEntryProtoR\x19quantParameterTensorNames\"@\n" +
	"\x16StringStringEntryProto\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x95\x04\n" +
	"\n" +
	"ModelProto\x12\x1d\n" +
	"\n" +
	"ir_version\x18\x01 \x01(\x03R\tirVersion\x12B\n" +
	"\fopset_import\x18\b \x03(\v2\x1f.checkpoints.OperatorSetIdProtoR\vopsetImport\x12#\n" +
	"\rproducer_name\x18\x02 \x01(\tR\fproducerName\x12)\n" +
	"\x10producer_version\x18\x03 \x01(\tR\x0fproducerVersion\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\x12#\n" +
	"\rmodel_version\x18\x05 \x01(\x03R\fmodelVersion\x12\x1d\n" +
	"\n" +
	"doc_string\x18\x06 \x01(\tR\tdocString\x12-\n" +
	"\x05graph\x18\a \x01(\v2\x17.checkpoints.GraphProtoR\x05graph\x12J\n" +
	"\x0emetadata_props\x18\x0e \x03(\v2#.checkpoints.StringStringEntryProtoR\rmetadataProps\x12C\n" +
	"\rtraining_info\x18\x14 \x03(\v2\x1e.checkpoints.TrainingInfoProtoR\ftrainingInfo\x128\n" +
	"\tfunctions\x18\x19 \x03(\v2\x1a.checkpoints.FunctionProtoR\tfunctions\"\x8b\x01\n" +
	"\x11TrainingInfoProto\x12?\n" +
	"\x0einitialization\x18\x01 \x01(\v2\x17.checkpoints.GraphProtoR\x0einitialization\x125\n" +
	"\talgorithm\x18\x02 \x01(\v2\x17.checkpoints.GraphProtoR\talgorithm\"\x96\x02\n" +
	"\rFunctionProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05input\x18\x04 \x03(\tR\x05input\x12\x16\n" +
	"\x06output\x18\x05 \x03(\tR\x06output\x12\x1c\n" +
	"\tattribute\x18\x06 \x03(\tR\tattribute\x12*\n" +
	"\x04node\x18\a \x03(\v2\x16.checkpoints.NodeProtoR\x04node\x12\x1d\n" +
	"\n" +
	"doc_string\x18\b \x01(\tR\tdocString\x12B\n" +
	"\fopset_import\x18\t \x03(\v2\x1f.checkpoints.OperatorSetIdProtoR\vopsetImport\x12\x16\n" +
	"\x06domain\x18\n" +
	" \x01(\tR\x06domain*\xe6\x01\n" +
	"\x14TensorProto_DataType\x12\r\n" +
	"\tUNDEFINED\x10\x00\x12\t\n" +
	"\x05FLOAT\x10\x01\x12\t\n" +
	"\x05UINT8\x10\x02\x12\b\n" +
	"\x04INT8\x10\x03\x12\n" +
	"\n" +
	"\x06UINT16\x10\x04\x12\t\n" +
	"\x05INT16\x10\x05\x12\t\n" +
	"\x05INT32\x10\x06\x12\t\n" +
	"\x05INT64\x10\a\x12\n" +
	"\n" +
	"\x06STRING\x10\b\x12\b\n" +
	"\x04BOOL\x10\t\x12\v\n" +
	"\aFLOAT16\x10\n" +
	"\x12\n" +
	"\n" +
	"\x06DOUBLE\x10\v\x12\n" +
	"\n" +
	"\x06UINT32\x10\f\x12\n" +
	"\n" +
	"\x06UINT64\x10\r\x12\r\n" +
	"\tCOMPLEX64\x10\x0e\x12\x0e\n" +
	"\n" +
	"COMPLEX128\x10\x0f\x12\f\n" +
	"\bBFLOAT16\x10\x10*\xb3\x02\n" +
	"\x1cAttributeProto_AttributeType\x12\x12\n" +
	"\x0eUNDEFINED_ATTR\x10\x00\x12\x0e\n" +
	"\n" +
	"FLOAT_ATTR\x10\x01\x12\f\n" +
	"\bINT_ATTR\x10\x02\x12\x0f\n" +
	"\vSTRING_ATTR\x10\x03\x12\x0f\n" +
	"\vTENSOR_ATTR\x10\x04\x12\x0e\n" +
	"\n" +
	"GRAPH_ATTR\x10\x05\x12\x16\n" +
	"\x12SPARSE_TENSOR_ATTR\x10\v\x12\x13\n" +
	"\x0fTYPE_PROTO_ATTR\x10\r\x12\x0f\n" +
	"\vFLOATS_ATTR\x10\x06\x12\r\n" +
	"\tINTS_ATTR\x10\a\x12\x10\n" +
	"\fSTRINGS_ATTR\x10\b\x12\x10\n" +
	"\fTENSORS_ATTR\x10\t\x12\x0f\n" +
	"\vGRAPHS_ATTR\x10\n" +
	"\x12\x17\n" +
	"\x13SPARSE_TENSORS_ATTR\x10\f\x12\x14\n" +
	"\x10TYPE_PROTOS_ATTR\x10\x0eB)Z'github.com/tsawler/go-metal/checkpointsb\x06proto3"

var (
	file_checkpoints_onnx_proto_rawDescOnce sync.Once
	file_checkpoints_onnx_proto_rawDescData []byte
)

func file_checkpoints_onnx_proto_rawDescGZIP() []byte {
	file_checkpoints_onnx_proto_rawDescOnce.Do(func() {
		file_checkpoints_onnx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_checkpoints_onnx_proto_rawDesc), len(file_checkpoints_onnx_proto_rawDesc)))
	})
	return file_checkpoints_onnx_proto_rawDescData
}

var file_checkpoints_onnx_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_checkpoints_onnx_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_checkpoints_onnx_proto_goTypes = []any{
	(TensorProto_DataType)(0),          // 0: checkpoints.TensorProto_DataType
	(AttributeProto_AttributeType)(0),  // 1: checkpoints.AttributeProto_AttributeType
	(*Version)(nil),                    // 2: checkpoints.Version
	(*OperatorSetIdProto)(nil),         // 3: checkpoints.OperatorSetIdProto
	(*TensorShapeProto)(nil),           // 4: checkpoints.TensorShapeProto
	(*TypeProto)(nil),                  // 5: checkpoints.TypeProto
	(*ValueInfoProto)(nil),             // 6: checkpoints.ValueInfoProto
	(*AttributeProto)(nil),             // 7: checkpoints.AttributeProto
	(*TensorProto)(nil),                // 8: checkpoints.TensorProto
	(*SparseTensorProto)(nil),          // 9: checkpoints.SparseTensorProto
	(*NodeProto)(nil),                  // 10: checkpoints.NodeProto
	(*GraphProto)(nil),                 // 11: checkpoints.GraphProto
	(*TensorAnnotation)(nil),           // 12: checkpoints.TensorAnnotation
	(*StringStringEntryProto)(nil),     // 13: checkpoints.StringStringEntryProto
	(*ModelProto)(nil),                 // 14: checkpoints.ModelProto
	(*TrainingInfoProto)(nil),          // 15: checkpoints.TrainingInfoProto
	(*FunctionProto)(nil),              // 16: checkpoints.FunctionProto
	(*TensorShapeProto_Dimension)(nil), // 17: checkpoints.TensorShapeProto.Dimension
	(*TypeProto_Tensor)(nil),           // 18: checkpoints.TypeProto.Tensor
	(*TensorProto_Segment)(nil),        // 19: checkpoints.TensorProto.Segment
}
var file_checkpoints_onnx_proto_depIdxs = []int32{
	17, // 0: checkpoints.TensorShapeProto.dim:type_name -> checkpoints.TensorShapeProto.Dimension
	18, // 1: checkpoints.TypeProto.tensor_type:type_name -> checkpoints.TypeProto.Tensor
	5,  // 2: checkpoints.ValueInfoProto.type:type_name -> checkpoints.TypeProto
	1,  // 3: checkpoints.AttributeProto.type:type_name -> checkpoints.AttributeProto_AttributeType
	8,  // 4: checkpoints.AttributeProto.t:type_name -> checkpoints.TensorProto
	11, // 5: checkpoints.AttributeProto.g:type_name -> checkpoints.GraphProto
	9,  // 6: checkpoints.AttributeProto.sparse_tensor:type_name -> checkpoints.SparseTensorProto
	5,  // 7: checkpoints.AttributeProto.tp:type_name -> checkpoints.TypeProto
	8,  // 8: checkpoints.AttributeProto.tensors:type_name -> checkpoints.TensorProto
	11, // 9: checkpoints.AttributeProto.graphs:type_name -> checkpoints.GraphProto
	9,  // 10: checkpoints.AttributeProto.sparse_tensors:type_name -> checkpoints.SparseTensorProto
	5,  // 11: checkpoints.AttributeProto.type_protos:type_name -> checkpoints.TypeProto
	0,  // 12: checkpoints.TensorProto.data_type:type_name -> checkpoints.TensorProto_DataType
	19, // 13: checkpoints.TensorProto.segment:type_name -> checkpoints.TensorProto.Segment
	8,  // 14: checkpoints.SparseTensorProto.values:type_name -> checkpoints.TensorProto
	8,  // 15: checkpoints.SparseTensorProto.indices:type_name -> checkpoints.TensorProto
	7,  // 16: checkpoints.NodeProto.attribute:type_name -> checkpoints.AttributeProto
	10, // 17: checkpoints.GraphProto.node:type_name -> checkpoints.NodeProto
	8,  // 18: checkpoints.GraphProto.initializer:type_name -> checkpoints.TensorProto
	9,  // 19: checkpoints.GraphProto.sparse_initializer:type_name -> checkpoints.SparseTensorProto
	6,  // 20: checkpoints.GraphProto.input:type_name -> checkpoints.ValueInfoProto
	6,  // 21: checkpoints.GraphProto.output:type_name -> checkpoints.ValueInfoProto
	6,  // 22: checkpoints.GraphProto.value_info:type_name -> checkpoints.ValueInfoProto
	12, // 23: checkpoints.GraphProto.quantization_annotation:type_name -> checkpoints.TensorAnnotation
	13, // 24: checkpoints.TensorAnnotation.quant_parameter_tensor_names:type_name -> checkpoints.StringStringEntryProto
	3,  // 25: checkpoints.ModelProto.opset_import:type_name -> checkpoints.OperatorSetIdProto
	11, // 26: checkpoints.ModelProto.graph:type_name -> checkpoints.GraphProto
	13, // 27: checkpoints.ModelProto.metadata_props:type_name -> checkpoints.StringStringEntryProto
	15, // 28: checkpoints.ModelProto.training_info:type_name -> checkpoints.TrainingInfoProto
	16, // 29: checkpoints.ModelProto.functions:type_name -> checkpoints.FunctionProto
	11, // 30: checkpoints.TrainingInfoProto.initialization:type_name -> checkpoints.GraphProto
	11, // 31: checkpoints.TrainingInfoProto.algorithm:type_name -> checkpoints.GraphProto
	10, // 32: checkpoints.FunctionProto.node:type_name -> checkpoints.NodeProto
	3,  // 33: checkpoints.FunctionProto.opset_import:type_name -> checkpoints.OperatorSetIdProto
	0,  // 34: checkpoints.TypeProto.Tensor.elem_type:type_name -> checkpoints.TensorProto_DataType
	4,  // 35: checkpoints.TypeProto.Tensor.shape:type_name -> checkpoints.TensorShapeProto
	36, // [36:36] is the sub-list for method output_type
	36, // [36:36] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_checkpoints_onnx_proto_init() }
func file_checkpoints_onnx_proto_init() {
	if File_checkpoints_onnx_proto != nil {
		return
	}
	file_checkpoints_onnx_proto_msgTypes[3].OneofWrappers = []any{
		(*TypeProto_TensorType)(nil),
	}
	file_checkpoints_onnx_proto_msgTypes[15].OneofWrappers = []any{
		(*TensorShapeProto_Dimension_DimValue)(nil),
		(*TensorShapeProto_Dimension_DimParam)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_checkpoints_onnx_proto_rawDesc), len(file_checkpoints_onnx_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_checkpoints_onnx_proto_goTypes,
		DependencyIndexes: file_checkpoints_onnx_proto_depIdxs,
		EnumInfos:         file_checkpoints_onnx_proto_enumTypes,
		MessageInfos:      file_checkpoints_onnx_proto_msgTypes,
	}.Build()
	File_checkpoints_onnx_proto = out.File
	file_checkpoints_onnx_proto_goTypes = nil
	file_checkpoints_onnx_proto_depIdxs = nil
}
